#!/bin/bash

# Para ASCII Art and Header
echo -e "\n\033[1;36m"
cat << "EOF"



  _____  _______   __
 |  __ \|  __ \ \ / /
 | |__) | |  | \ V / 
 |  _  /| |  | |> <  
 | | \ \| |__| / . \ 
 |_|  \_\_____/_/ \_\
                     

                                
                              
 🤍 Ubuntu Installer In Github - github.com/Rdx

EOF
echo -e "\033[0m"

echo -e "\033[1;34mStarting Installation of Ubuntu\033[0m"
echo "-------------------------------------"

# Installation Steps
commands=(
  "git clone https://github.com/hopingboyz/ubuntu22.04"
  "cd ubuntu22.04"
  "docker build -t ubuntu-vm ."
  "docker run --privileged -p 6080:6080 -p 2221:2222 -v $PWD/vmdata:/data ubuntu-vm"
)

# Execute commands with progress
for i in "${!commands[@]}"; do
  echo -e "\033[1;33m[$((i+1))/14] Executing:\033[0m \033[0;35m${commands[$i]}\033[0m"
  eval "${commands[$i]}"
  if [ $? -ne 0 ]; then
    echo -e "\033[1;31mError occurred at step $((i+1)). Aborting installation.\033[0m"
    exit 1
  fi
done

# Completion Message
echo -e "\n\033[1;32m-------------------------------------\033[0m"
echo -e "\033[1;32m Credit Also Goes to HopingBoyz Note Script Made By Rdx 🎉\033[0m"
echo -e "\033[1;35m           User:root pass:root Made By Para\033[0m"
echo -e "\033[1;35m       github.com/Para\033[0m"
echo -e "\033[1;32m-------------------------------------\033[0m"
